_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.15
        t:
            "1":
                - 1
                - 5
                - 9
                - 53
                - 55
            "2":
                - 1
                - 5
                - 9
                - 53
                - 55
            "3":
                - 17
                - 23
                - 55
            "4": 3.8.15
            "5": 0.19.1
            "8":
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.1
            "13": windows-amd64
